[package]
name = "r349"
version = "0.1.0"
authors = ["Pavel <pavel.shackih@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.98"
serde-xml-rs = "0.3.1"
serde_derive = "1.0.98"